name = "VaspTools"
uuid = "c8ffe67e-a47f-49bc-b97c-c29ee461a3c6"
authors = ["martin <ga63loc@mytum.de>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
